server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: kimminhyoung
    password: cwkim091002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: dev-0123456789abcdef-0123456789abcdef-0123456789abcdef-01234567z
  access-token-expiration: 1800      # 30분(초)
  refresh-token-expiration: 1209600 # 14일(초)

cors:
  allowed-origins:
    - http://localhost:5173   # React 개발 서버
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true